services:
  db:
    image: postgis/postgis:15-3.4
    container_name: lanes_postgis_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lanes
    ports:
      - "5432:5432"
    volumes:
      - lanes_db_data:/var/lib/postgresql/data

  osrm:
    image: ghcr.io/project-osrm/osrm-backend
    container_name: lanes_osrm
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data/osrm:/data
    command: "osrm-routed --algorithm mld /data/philippines-latest.osrm"

volumes:
  lanes_db_data:
