services:
  db:
    image: postgis/postgis:15-3.4
    container_name: lanes_postgis_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lanes
    ports:
      - "5432:5432"
    volumes:
      - lanes_db_data:/var/lib/postgresql/data

  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: lanes_valhalla
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - ./data/valhalla/custom_files:/custom_files

volumes:
  lanes_db_data:
