"""add_audit_and_normalization_upgrades

Revision ID: 0cff9d1ff136
Revises: 
Create Date: 2026-07-01 22:42:23.654449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cff9d1ff136'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_table', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('fk_audit_logs_admin_id_users'), ondelete='SET NULL'),
    sa.CheckConstraint("ip_address IS NULL OR ip_address ~ '^[0-9a-fA-F:.]+$'", name='chk_ip_address'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('flood_report_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['flood_reports.id'], name=op.f('fk_flood_report_locations_report_id_flood_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flood_report_locations'))
    )
    op.create_index(op.f('ix_flood_report_locations_id'), 'flood_report_locations', ['id'], unique=False)
    op.create_index(op.f('ix_flood_report_locations_location_name'), 'flood_report_locations', ['location_name'], unique=False)
    op.create_index(op.f('ix_flood_report_locations_report_id'), 'flood_report_locations', ['report_id'], unique=False)
    op.create_index(op.f('ix_flood_avoidance_zones_report_id'), 'flood_avoidance_zones', ['report_id'], unique=False)
    op.add_column('flood_reports', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('flood_reports', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_flood_reports_user_id'), 'flood_reports', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_flood_reports_user_id_users'), 'flood_reports', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_flood_reports_user_id_users'), 'flood_reports', type_='foreignkey')
    op.drop_index(op.f('ix_flood_reports_user_id'), table_name='flood_reports')
    op.drop_column('flood_reports', 'source_url')
    op.drop_column('flood_reports', 'user_id')
    op.drop_index(op.f('ix_flood_avoidance_zones_report_id'), table_name='flood_avoidance_zones')
    op.drop_index(op.f('ix_flood_report_locations_report_id'), table_name='flood_report_locations')
    op.drop_index(op.f('ix_flood_report_locations_location_name'), table_name='flood_report_locations')
    op.drop_index(op.f('ix_flood_report_locations_id'), table_name='flood_report_locations')
    op.drop_table('flood_report_locations')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
