"""Add upvotes and downvotes to reports

Revision ID: 186d1becfd1d
Revises: c5486fdead1c
Create Date: 2026-07-11 01:00:00.672986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186d1becfd1d'
down_revision: Union[str, Sequence[str], None] = 'c5486fdead1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_reports', sa.Column('upvotes', sa.Integer(), nullable=False))
    op.add_column('flood_reports', sa.Column('downvotes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flood_reports', 'downvotes')
    op.drop_column('flood_reports', 'upvotes')
    # ### end Alembic commands ###
