"""Add comments table

Revision ID: 1cd978d537e9
Revises: c94b30dc95b3
Create Date: 2026-07-11 17:53:43.751554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cd978d537e9'
down_revision: Union[str, Sequence[str], None] = 'c94b30dc95b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flood_reports', 'source',
               existing_type=postgresql.ENUM('twitter', 'facebook', 'direct_user', 'manual_seeder', name='reportsource_enum'),
               type_=sa.Enum('twitter', 'facebook', 'direct_user', 'manual_seeder', name='reportsource', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('flood_reports', 'severity',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'extreme', name='reportseverity_enum'),
               type_=sa.Enum('low', 'medium', 'high', 'extreme', name='reportseverity', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('flood_reports', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='reportstatus_enum'),
               type_=sa.Enum('pending', 'approved', 'rejected', name='reportstatus', native_enum=False, length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flood_reports', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='reportstatus', native_enum=False, length=50),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='reportstatus_enum'),
               existing_nullable=False)
    op.alter_column('flood_reports', 'severity',
               existing_type=sa.Enum('low', 'medium', 'high', 'extreme', name='reportseverity', native_enum=False, length=50),
               type_=postgresql.ENUM('low', 'medium', 'high', 'extreme', name='reportseverity_enum'),
               existing_nullable=False)
    op.alter_column('flood_reports', 'source',
               existing_type=sa.Enum('twitter', 'facebook', 'direct_user', 'manual_seeder', name='reportsource', native_enum=False, length=50),
               type_=postgresql.ENUM('twitter', 'facebook', 'direct_user', 'manual_seeder', name='reportsource_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
