"""Add flood report survey table

Revision ID: 2abb5c5c48d2
Revises: 8abf9708ab32
Create Date: 2026-07-15 00:35:56.769195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abb5c5c48d2'
down_revision: Union[str, Sequence[str], None] = '8abf9708ab32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flood_report_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('passable_vehicles', sa.String(length=500), nullable=True),
    sa.Column('hidden_hazards', sa.Enum('yes', 'no', 'unsure', name='hazardpresence', native_enum=False, length=50), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['flood_reports.id'], name=op.f('fk_flood_report_surveys_report_id_flood_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flood_report_surveys'))
    )
    op.create_index(op.f('ix_flood_report_surveys_id'), 'flood_report_surveys', ['id'], unique=False)
    op.create_index(op.f('ix_flood_report_surveys_report_id'), 'flood_report_surveys', ['report_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flood_report_surveys_report_id'), table_name='flood_report_surveys')
    op.drop_index(op.f('ix_flood_report_surveys_id'), table_name='flood_report_surveys')
    op.drop_table('flood_report_surveys')
    # ### end Alembic commands ###
