"""add location_tag to community_posts

Revision ID: 5bf8100fd0b0
Revises: 8c0e91b2bd30
Create Date: 2026-07-22 22:04:12.107534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf8100fd0b0'
down_revision: Union[str, Sequence[str], None] = '8c0e91b2bd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_posts', sa.Column('location_tag', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_posts', 'location_tag')
    # ### end Alembic commands ###
