"""Add image_url to FloodReport

Revision ID: 74cc9243adc1
Revises: 9bedc25204a9
Create Date: 2026-07-09 22:11:43.060087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cc9243adc1'
down_revision: Union[str, Sequence[str], None] = '9bedc25204a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_reports', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flood_reports', 'image_url')
    # ### end Alembic commands ###
