"""Add VisitorCount model

Revision ID: 771b52dbed1b
Revises: 5781ca7a8e88
Create Date: 2026-07-13 22:45:09.749842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771b52dbed1b'
down_revision: Union[str, Sequence[str], None] = '5781ca7a8e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_visitors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitor_counts'))
    )
    op.create_index(op.f('ix_visitor_counts_id'), 'visitor_counts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_counts_id'), table_name='visitor_counts')
    op.drop_table('visitor_counts')
    # ### end Alembic commands ###
