"""Add approved_at to FloodReport

Revision ID: 8abf9708ab32
Revises: 771b52dbed1b
Create Date: 2026-07-14 23:38:38.299930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abf9708ab32'
down_revision: Union[str, Sequence[str], None] = '771b52dbed1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_reports', sa.Column('approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flood_reports', 'approved_at')
    # ### end Alembic commands ###
