"""add barangay to flood_reports

Revision ID: 8c0e91b2bd30
Revises: ba57bfad5c80
Create Date: 2026-07-16 23:35:27.960967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0e91b2bd30'
down_revision: Union[str, Sequence[str], None] = 'ba57bfad5c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_reports', sa.Column('barangay', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_flood_reports_barangay'), 'flood_reports', ['barangay'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flood_reports_barangay'), table_name='flood_reports')
    op.drop_column('flood_reports', 'barangay')
    # ### end Alembic commands ###
