"""add phase 3 models

Revision ID: ba57bfad5c80
Revises: 577203e96d7b
Create Date: 2026-07-16 15:18:26.073329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba57bfad5c80'
down_revision: Union[str, Sequence[str], None] = '577203e96d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LIKE', 'COMMENT', 'SYSTEM', name='notificationtype', native_enum=False, length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flood_report_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flood_report_id'], ['flood_reports.id'], name=op.f('fk_community_posts_flood_report_id_flood_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_community_posts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_posts'))
    )
    op.create_index(op.f('ix_community_posts_flood_report_id'), 'community_posts', ['flood_report_id'], unique=False)
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_index(op.f('ix_community_posts_user_id'), 'community_posts', ['user_id'], unique=False)
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_comments_report_id'), table_name='comments')
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.drop_constraint(op.f('fk_comments_report_id_flood_reports'), 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_post_id_community_posts'), 'comments', 'community_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'report_id')
    op.add_column('post_interactions', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_post_interactions_report_id'), table_name='post_interactions')
    op.create_index(op.f('ix_post_interactions_post_id'), 'post_interactions', ['post_id'], unique=False)
    op.drop_constraint(op.f('fk_post_interactions_report_id_flood_reports'), 'post_interactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_post_interactions_post_id_community_posts'), 'post_interactions', 'community_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_interactions', 'report_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_interactions', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_post_interactions_post_id_community_posts'), 'post_interactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_post_interactions_report_id_flood_reports'), 'post_interactions', 'flood_reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_post_interactions_post_id'), table_name='post_interactions')
    op.create_index(op.f('ix_post_interactions_report_id'), 'post_interactions', ['report_id'], unique=False)
    op.drop_column('post_interactions', 'post_id')
    op.add_column('comments', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_comments_post_id_community_posts'), 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_report_id_flood_reports'), 'comments', 'flood_reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.create_index(op.f('ix_comments_report_id'), 'comments', ['report_id'], unique=False)
    op.drop_column('comments', 'post_id')
    op.drop_index(op.f('ix_community_posts_user_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_flood_report_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
