"""Add Community Feed and Enums

Revision ID: c94b30dc95b3
Revises: 186d1becfd1d
Create Date: 2026-07-11 15:55:48.284893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c94b30dc95b3'
down_revision: Union[str, Sequence[str], None] = '186d1becfd1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_reports', sa.Column('human_readable_location', sa.String(length=255), nullable=True))
    op.add_column('flood_reports', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    
    # Create enum types manually if needed, but postgresql_using handles the cast
    sa.Enum('twitter', 'facebook', 'direct_user', 'manual_seeder', name='reportsource_enum').create(op.get_bind(), checkfirst=True)
    op.alter_column('flood_reports', 'source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('twitter', 'facebook', 'direct_user', 'manual_seeder', name='reportsource_enum'),
               existing_nullable=False,
               postgresql_using='source::reportsource_enum')
               
    sa.Enum('low', 'medium', 'high', 'extreme', name='reportseverity_enum').create(op.get_bind(), checkfirst=True)
    op.alter_column('flood_reports', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('low', 'medium', 'high', 'extreme', name='reportseverity_enum'),
               existing_nullable=False,
               postgresql_using='severity::reportseverity_enum')
               
    sa.Enum('pending', 'approved', 'rejected', name='reportstatus_enum').create(op.get_bind(), checkfirst=True)
    op.alter_column('flood_reports', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'approved', 'rejected', name='reportstatus_enum'),
               existing_nullable=False,
               postgresql_using='status::reportstatus_enum')
               
    op.drop_column('flood_reports', 'upvotes')
    op.drop_column('flood_reports', 'downvotes')
    op.drop_column('flood_reports', 'extracted_locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_reports', sa.Column('extracted_locations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('flood_reports', sa.Column('downvotes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('flood_reports', sa.Column('upvotes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.alter_column('flood_reports', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reportstatus_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('flood_reports', 'severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EXTREME', name='reportseverity_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('flood_reports', 'source',
               existing_type=sa.Enum('TWITTER', 'FACEBOOK', 'USER_REPORT', name='reportsource_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('flood_reports', 'is_public')
    op.drop_column('flood_reports', 'human_readable_location')
    # ### end Alembic commands ###
