"""Add depth to flood_reports

Revision ID: d34f2a2e5eae
Revises: 5bf8100fd0b0
Create Date: 2026-07-23 00:13:46.850675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34f2a2e5eae'
down_revision: Union[str, Sequence[str], None] = '5bf8100fd0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flood_reports', sa.Column('depth', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flood_reports', 'depth')
    # ### end Alembic commands ###
